version: 2.1

orbs:
  gem: doximity/gem-publisher@0.0.5

executors:
  ruby-latest:
    resource_class: small
    docker:
      - image: circleci/ruby:2.6.5

# yaml anchor filters
master_only: &master_only
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/
pr_only: &pr_only
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/
version_tags_only: &version_tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

jobs:
  build:
    executor: ruby-latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}-
      - run:
          name: Install Bundler specific version
          command: |
            gem install bundler --version "~> 1.17" --force
      - run:
          name: Install Ruby Dependencies
          command: bundle check --path=vendor/bundle || bundle install --local --frozen --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}-
          paths:
            - vendor/bundle
      #- run:
      #    name: Run Tests
      #    command: bundle exec rake ci:specs
      #- store_test_results:
      #    name: Store test results
      #    path: tmp/test-results
      - run:
          name: Run Rubocop
          command: bundle exec rake ci:rubocop
      - run:
          name: Build documentation
          command: bundle exec rake ci:doc
      - store_artifacts:
          name: Saves documentation
          path: doc
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

workflows:
  version: 2

  pull-requests:
    jobs:
      - build:
          <<: *pr_only
      - gem/build:
          requires:
            - build
      - pre-release-approval:
          type: approval
          requires:
            - gem/build
      - gem/publish:
          to_jfrog: true
          pre_release: true
          requires:
            - pre-release-approval
          context: artifact_publishing

  trunk:
    jobs:
      - build:
          <<: *master_only
      - gem/build:
          requires:
            - build

  final-release:
    jobs:
      - build:
          <<: *version_tags_only
      - gem/build:
          <<: *version_tags_only
          requires:
            - build
      - gem/publish:
          <<: *version_tags_only
          to_jfrog: true
          pre_release: false
          requires:
            - gem/build
          context: artifact_publishing
